name = "ctrlBlocks"
uuid = "d57ef60f-eceb-4bed-8af3-558642879c1f"
authors = ["Jan Lauble"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
