name = "ctrlBlocks"
uuid = "d57ef60f-eceb-4bed-8af3-558642879c1f"
authors = ["Jan Lauble"]
version = "1.0.0-DEV"

[deps]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test", "SafeTestsets"]
